import type { NextPage } from 'next'
import Head from 'next/head'
import { useEffect, useState } from 'react'
import Header from '../components/Header/Header'
import TableComparative from '../components/Table/TableComparative'
import { TableValues } from '../constants/constants'
import { getProducts } from '../helpers/request'
import { productsInterface } from '../interfaces/Products'
import Label from '../components/Label/Label'

const Home: NextPage = () => {
  const [data, setData] = useState<Array<productsInterface>>([])
  useEffect(() => {
    getProducts().then((resp) => {
      setData(resp)
    })
  }, [])

  return (
    <div className='container'>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Header />
      <main className='main'>
        <Label title='Comparative Analysis'></Label>
        <TableComparative data={data} tableValues={TableValues} />
      </main>
    </div>
  )
}

export default Home
