import type { NextPage } from 'next'
import Head from 'next/head'
import { useEffect, useState } from 'react'
import Header from '../components/Header/Header'
import TableComparative from '../components/Table/TableComparative'
import { TableValues } from '../constants/constants'
import { getProducts, getShareChart, getPriceEvolution } from '../helpers/request'
import { productsInterface } from '../interfaces/Products'
import { ShareInterface } from '../interfaces/Share'
import Label from '../components/Label/Label'
import ProductChart from '../components/ProductChart/ProductChart'
import PriceEvolution from '../components/PriceEvolution/PriceEvolution'
import { EvolutionInterface } from '../interfaces/Evolution'

const Home: NextPage = () => {
  const [data, setData] = useState<Array<productsInterface>>([])
  const [share, setShare] = useState<Array<ShareInterface>>([])
  const [evolution, setEvolution] = useState<Array<EvolutionInterface>>([])
  useEffect(() => {
    getProducts().then((resp) => {
      setData(resp)
    })
    getShareChart().then((resp) => {
      setShare(resp)
    })
    getPriceEvolution().then((resp) => {
      setEvolution(resp)
    })
  }, []);

  return (
    <div className='container'>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Header />
      <main className='main'>
        <div className='charts'>
          <div>
            <Label title='Price Evolution'></Label>
            {
              evolution.length !== 0 ?
                <PriceEvolution data={evolution} />
                :
                <span>Loading</span>
            }
          </div>
          <div>
            <Label title='Presence Share by Product'></Label>
            {
              share.length !== 0 ?
                <ProductChart data={share} />
                :
                <span>Loading</span>
            }
          </div>
        </div>
        <Label title='Comparative Analysis'></Label>
        <TableComparative data={data} tableValues={TableValues} />
      </main>
    </div>
  )
}

export default Home
